### ISSUE TITLE
[Frontend] Error: volto-authomatic@github:collective/volto-authomatic#spanish_translation: Couldn't resolve "spanish_translation" as either a commit, a tag, or a head

### ISSUE THREAD

**Issue by JuanLP06** [ScrumLATAMComunidad/scrumlatamcomunidad.com#78]
Este error se da cuando se ejecuta el comando "make build-frontend"

Log:
```
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: volto-authomatic@github:collective/volto-authomatic#spanish_translation: Couldn't resolve "spanish_translation" as either a commit, a tag, or a head
    at a (/home/jlopez/slc-sitioweb/frontend/.yarn/releases/yarn-3.2.3.cjs:593:6619)
    at UN (/home/jlopez/slc-sitioweb/frontend/.yarn/releases/yarn-3.2.3.cjs:593:6828)
    at async jN.getCandidates (/home/jlopez/slc-sitioweb/frontend/.yarn/releases/yarn-3.2.3.cjs:593:11800)
    at async Bd.getCandidates (/home/jlopez/slc-sitioweb/frontend/.yarn/releases/yarn-3.2.3.cjs:391:1241)
    at async Bd.getCandidates (/home/jlopez/slc-sitioweb/frontend/.yarn/releases/yarn-3.2.3.cjs:391:1241)
    at async /home/jlopez/slc-sitioweb/frontend/.yarn/releases/yarn-3.2.3.cjs:439:7756
    at async Tg (/home/jlopez/slc-sitioweb/frontend/.yarn/releases/yarn-3.2.3.cjs:390:11148)
    at async ce (/home/jlopez/slc-sitioweb/frontend/.yarn/releases/yarn-3.2.3.cjs:439:7738)
➤ YN0000: └ Completed in 6s 426ms
➤ YN0000: Failed with errors in 6s 445ms
make[1]: *** [Makefile:52: install] Error 1
make[1]: Leaving directory '/home/jlopez/slc-sitioweb/frontend'
make: *** [Makefile:36: build-frontend] Error 2.
```

**Comment by macagua** [comment]
@JuanLP06 ya detecte la falla, la configuracion de instalacion apunta a la rama  https://github.com/collective/volto-authomatic/tree/spanish_translation esta ya no existe por que se fuciono a la https://github.com/collective/volto-authomatic/tree/main via commit 05ff301

Ya corrijo la configuracion de instalacion del paquete[ volto-authomatic](https://www.npmjs.com/package/@plone-collective/volto-authomatic)

**Comment by macagua** [comment]
@JuanLP06 listo, vuelve a hacer ``git pull origin develop`` y luego ``git rebase develop`` dentro de tu branch, luego ejecuta ``make build-frontend`` confirma que el error este resuelto

**Comment by macagua** [comment]
@JuanLP06 acabo de revisar en mi local y funciona muy bien, necesito que me confirmes por aca luego que hagas la prueba en tu local, como previamente te indique, si ya te funciona para cerrar esta tarea!

**Comment by macagua** [comment]
@emicmiranda esta tarea esta validada por @JuanLP06 se da por hecha!
