### ISSUE TITLE
[Backend] Couldn't import pas.plugins, No module named 'pas'

### ISSUE THREAD

**Issue by JuanLP06** [ScrumLATAMComunidad/scrumlatamcomunidad.com#79]
Este error se produce cuando se ejecuta el comnado make start-backend

```
jlopez@JUANPC:~/slc-sitioweb$ make start-backend
+ dirname /home/jlopez/slc-sitioweb/Makefile
+ make -C ./backend/ start
make[1]: Entering directory '/home/jlopez/slc-sitioweb/backend'
+ which python3
+ python3 -c 'import sys; print((int(sys.version_info[0]), int(sys.version_info[1])) >= tuple(map(int, '\''3.8'\''.split('\''.'\''))))'
+ PYTHONWARNINGS=ignore
+ ./bin/runwsgi instance/etc/zope.ini
2023-07-12 10:49:17,142 INFO    [chameleon.config:38][MainThread] directory cache: /home/jlopez/slc-sitioweb/backend/instance/var/cache.
2023-07-12 10:49:20,631 INFO    [plone.volto:22][MainThread] Aliasing collective.folderish classes to plone.volto classes.
Traceback (most recent call last):
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/config.py", line 225, in resolve
    __import__(mname)
ModuleNotFoundError: No module named 'pas'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/fields.py", line 173, in fromUnicode
    value = self.context.resolve(name)
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/config.py", line 231, in resolve
    raise ConfigurationError(
zope.configuration.exceptions.ConfigurationError: ImportError: Couldn't import pas.plugins, No module named 'pas'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/config.py", line 1702, in toargs
    args[str(name)] = field.fromUnicode(s)
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/fields.py", line 175, in fromUnicode
    raise ValidationError(v).with_field_and_value(self, name)
zope.schema._bootstrapinterfaces.ValidationError: ImportError: Couldn't import pas.plugins, No module named 'pas'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jlopez/slc-sitioweb/backend/./bin/runwsgi", line 8, in <module>
    sys.exit(main())
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/Zope2/Startup/serve.py", line 251, in main
    return command.run()
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/Zope2/Startup/serve.py", line 189, in run
    app = self.loadapp(app_spec, name=app_name, relative_to=base,
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/Zope2/Startup/serve.py", line 220, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/paste/deploy/loadwsgi.py", line 248, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/paste/deploy/loadwsgi.py", line 273, in loadobj
    return context.create()
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/paste/deploy/loadwsgi.py", line 741, in create
    return self.object_type.invoke(self)
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/paste/deploy/loadwsgi.py", line 200, in invoke
    app = context.app_context.create()
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/paste/deploy/loadwsgi.py", line 741, in create
    return self.object_type.invoke(self)
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/paste/deploy/loadwsgi.py", line 138, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/paste/deploy/util.py", line 61, in fix_call
    val = callable(*args, **kw)
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/Zope2/Startup/run.py", line 61, in make_wsgi_app
    starter.prepare()
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/Zope2/Startup/starter.py", line 38, in prepare
    self.startZope()
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/Zope2/Startup/starter.py", line 94, in startZope
    Zope2.startup_wsgi()
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/Zope2/__init__.py", line 36, in startup_wsgi
    _startup()
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/Zope2/App/startup.py", line 126, in startup
    load_zcml()
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/Zope2/App/startup.py", line 41, in load_zcml
    load_site()
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/Zope2/App/zcml.py", line 45, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 663, in file
    include(context, name, package)
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 560, in include
    processxmlfile(f, context)
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 409, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python3.9/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.9/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.9/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "../Modules/pyexpat.c", line 459, in EndElement
  File "/usr/lib/python3.9/xml/sax/expatreader.py", line 381, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 395, in endElementNS
    self._handle_exception(ex, info)
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self.context.end()
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/config.py", line 703, in end
    self.stack.pop().finish()
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/config.py", line 873, in finish
    actions = self.handler(context, **args)
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 560, in include
    processxmlfile(f, context)
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 409, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python3.9/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.9/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.9/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "../Modules/pyexpat.c", line 459, in EndElement
  File "/usr/lib/python3.9/xml/sax/expatreader.py", line 381, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 395, in endElementNS
    self._handle_exception(ex, info)
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self.context.end()
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/config.py", line 703, in end
    self.stack.pop().finish()
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/config.py", line 873, in finish
    actions = self.handler(context, **args)
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 560, in include
    processxmlfile(f, context)
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 409, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python3.9/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.9/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.9/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "../Modules/pyexpat.c", line 459, in EndElement
  File "/usr/lib/python3.9/xml/sax/expatreader.py", line 381, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 395, in endElementNS
    self._handle_exception(ex, info)
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self.context.end()
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/config.py", line 703, in end
    self.stack.pop().finish()
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/config.py", line 872, in finish
    args = toargs(context, *self.argdata)
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/config.py", line 1704, in toargs
    reraise(
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/_compat.py", line 31, in reraise
    raise value.with_traceback(tb)
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/config.py", line 1702, in toargs
    args[str(name)] = field.fromUnicode(s)
  File "/home/jlopez/slc-sitioweb/backend/lib/python3.9/site-packages/zope/configuration/fields.py", line 175, in fromUnicode
    raise ValidationError(v).with_field_and_value(self, name)
zope.configuration.exceptions.ConfigurationError: Invalid value for 'package'
    File "/home/jlopez/slc-sitioweb/backend/instance/etc/site.zcml", line 16.2-16.36
    File "/home/jlopez/slc-sitioweb/backend/src/slc_sitioweb/src/slc_sitioweb/configure.zcml", line 18.2-18.38
    File "/home/jlopez/slc-sitioweb/backend/src/slc_sitioweb/src/slc_sitioweb/dependencies.zcml", line 6.2-6.46
    zope.schema._bootstrapinterfaces.ValidationError: ImportError: Couldn't import pas.plugins, No module named 'pas'
make[1]: *** [Makefile:158: start] Error 1
make[1]: Leaving directory '/home/jlopez/slc-sitioweb/backend'
make: *** [Makefile:57: start-backend] Error 2
```

**Comment by macagua** [comment]
@JuanLP06 una pregunta tu ejecutaste el comando ``make build-backend`` antes de iniciar el comando ``make start-backend``

**Comment by macagua** [comment]
@JuanLP06 una pregunta tu ejecutaste el comando ``make build-backend`` antes de iniciar el comando ``make start-backend`` confirma si el error persite o se resuelve por favor!

**Comment by macagua** [comment]
@JuanLP06 acabo de revisar en mi local y funciona muy bien, necesito que me confirmes por aca luego que hagas la prueba en tu local, como previamente te indique, si ya te funciona para cerrar esta tarea!

**Comment by macagua** [comment]
@emicmiranda esta tarea esta validada por @JuanLP06 se da por hecha!
